package com.huzhijian.nexusagentweb.domain;



import java.io.Serializable;

import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Builder;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

/**
* 用户表
* @TableName user
*/
@Data
@Builder
@TableName(value ="users")
public class User implements Serializable {

    /**
    * 
    */
    // 补上主键声明：原先只有校验注解、没有 @TableId，
    // 导致 MyBatis-Plus 不认这是主键——getById/updateById/removeById 会失败，
    // 且 save() 后 user.getId() 可能取不到值（register 里要用它签 JWT）。
    // 数据库侧对应 users.id 为 GENERATED BY DEFAULT AS IDENTITY，故用 AUTO。
    @TableId(type = IdType.AUTO)
    @NotNull(message="[]不能为空")
    private Long id;
    /**
    * 邮箱，唯一
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String email;
    /**
    * 
    */
    @NotBlank(message="[]不能为空")
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String username;
    /**
    * 使用bcrypt算法加密
    */
    private String password;
    /**
    * 
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String avatarImg;
    /**
    *
    */
    private Date registerTime;
    /**
    * API限制，每个用户只能使用100次
    */
    @NotNull(message="[API限制，每个用户只能使用100次]不能为空")
    private Integer apiQuota;
    /**
    * githubID
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String githubId;

}
