package com.huzhijian.nexusagentweb.domain;



import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Builder;
import lombok.Data;
import org.hibernate.validator.constraints.Length;

/**
* 用户表
* @TableName user
*/
@Data
@Builder
@TableName(value ="users")
public class User implements Serializable {

    /**
    * 
    */
    // 补上主键声明：原先只有校验注解、没有 @TableId，
    // 导致 MyBatis-Plus 不认这是主键——getById/updateById/removeById 会失败，
    // 且 save() 后 user.getId() 可能取不到值（register 里要用它签 JWT）。
    // 数据库侧对应 users.id 为 GENERATED BY DEFAULT AS IDENTITY，故用 AUTO。
    @TableId(type = IdType.AUTO)
    @NotNull(message="[]不能为空")
    private Long id;
    /**
    * 邮箱，唯一
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String email;
    /**
    * 
    */
    @NotBlank(message="[]不能为空")
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String username;
    /**
    * 使用bcrypt算法加密
    */
    private String password;
    /**
    * 
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String avatarImg;
    /**
    *
    */
    private Date registerTime;
    /**
    * API限制，每个用户只能使用100次
    */
    @NotNull(message="[API限制，每个用户只能使用100次]不能为空")
    private Integer apiQuota;
    /**
     * token 配额上限（累计）。**null 或 &lt;= 0 表示不限制**（默认放行，老用户行为不变）。
     * <p>
     * 对应 {@code docs/sql/003_add_user_token_quota.sql}；P2-8 新增。
     */
    private Long tokenQuota;
    /**
     * 已累计消耗的 token 总量，由对话结束时累加。
     * <p>
     * 周期类型为 {@code NONE} 时**单调递增、不清零**；
     * 设为 {@code DAILY}/{@code MONTHLY} 后会在跨周期时清零（P2-8 遗留，见 {@code docs/sql/007}）。
     */
    private Long tokenUsed;
    /**
     * token 配额的**重置周期**：{@code NONE}（默认，累计）/ {@code DAILY} / {@code MONTHLY}。
     * <p>
     * 存的是字符串而不是枚举，避开 MyBatis 枚举处理器在不同列类型上的坑；
     * 解析统一走 {@code QuotaPeriod.of(...)}（null/未知值都按 NONE 处理，
     * 这样 `007` 没执行时行为与 003 完全一致）。
     */
    private String tokenPeriod;
    /**
     * 当前周期的起点时间（**服务端本地时区**）。
     * 小于"本次算出的周期起点"时触发清零 —— 惰性重置，没有后台任务。
     */
    private LocalDateTime tokenPeriodStart;

    /**
     * 用户角色（{@code docs/sql/012}）：{@code NORMAL} / {@code TEST} / {@code VIP}。
     * <p>
     * 只决定**额度默认值**，不参与鉴权 —— 想给谁单独加额度，直接改
     * {@link #tokenQuota} / {@link #fileQuota} 即可（用户级列优先于角色）。
     * 存字符串而非枚举：与 {@link #tokenPeriod} 保持同一套做法，避开枚举处理器的坑。
     */
    private String role;

    /**
     * 每日「文件 + 产物」数量上限（{@code docs/sql/012}）。
     * <p>
     * {@code null} 或 {@code <= 0} 表示<b>不限制</b>（沿用 tokenQuota 的约定）。
     * 文件与产物共用一份额度 —— 它们都落在 {@code sys_file} 表，
     * 按 {@code create_time >= 当天 00:00} 统计条数，天然按天滚动，不需要重置。
     */
    private Long fileQuota;
    /**
    * githubID
    */
    @Size(max= 255,message="编码长度不能超过255")
    @Length(max= 255,message="编码长度不能超过255")
    private String githubId;

}
