-- ============================================================================
--  nexus-agent 数据库基线  001_baseline.sql
--  版本：2.0（重新设计版）      最后更新：2026-09-23
-- ============================================================================
--  这份脚本是**重新设计**的，不是从旧库照抄。
--
--  背景
--  开发库曾被自动程序清空过，灾后重建出来的结构是不完整的：
--    · 12 张表全部没有主键、唯一约束、外键，也没有任何索引
--    · sys_file 表不存在（文件上传功能会在运行期报 relation does not exist）
--    · knowledge_base_file 缺 file_name 列（知识库入库与详情查询都会报错）
--  旧数据已确认可全部舍弃（仅测试账号），因此本文件按「**代码实际需要什么**」
--  重新设计，依据是 nexus-agent-domain 的实体 + nexus-agent-mapper 的 XML
--  + Service 层真实 SQL 语句，逐项交叉推导。
--
--  ⚠️ 本文件是**破坏性**的：会先 DROP 再重建，清空所有业务数据。
--     仅用于初始化 / 重建。增量变更请新建 002_xxx.sql，不要修改本文件。
--
--  执行方式
--    psql -h <SERVICE_IP> -U postgres -d nexus_agent -f docs/sql/001_baseline.sql
--    或 Navicat：右键目标库 → 运行 SQL 文件
--
--  前置要求：目标库需可安装 pgvector 扩展（脚本已含 CREATE EXTENSION）。
-- ============================================================================


-- ============================================================================
-- 0. 清理旧结构
-- ============================================================================
-- 先删「有被引用关系」的子表，再删主表；顺序错会报依赖冲突。
-- skill_information / user_skill 是历史残留（代码中已无任何实体或 Mapper 使用），
-- 一并删除，避免继续堆积死表。
DROP TABLE IF EXISTS "public"."knowledge_base_file";
DROP TABLE IF EXISTS "public"."knowledge_embedding";
DROP TABLE IF EXISTS "public"."chat_memory";
DROP TABLE IF EXISTS "public"."chat_history_list";
DROP TABLE IF EXISTS "public"."user_memory";
DROP TABLE IF EXISTS "public"."user_config";
DROP TABLE IF EXISTS "public"."mcp_information";
DROP TABLE IF EXISTS "public"."skill_mcp_information";
DROP TABLE IF EXISTS "public"."system_log";
DROP TABLE IF EXISTS "public"."sys_file";
DROP TABLE IF EXISTS "public"."knowledge_base";
DROP TABLE IF EXISTS "public"."users";
-- 历史的死表
DROP TABLE IF EXISTS "public"."user_skill";
DROP TABLE IF EXISTS "public"."skill_information";

DROP TYPE IF EXISTS "public"."message_type";
DROP TYPE IF EXISTS "public"."upload_status";

-- 旧库遗留的手工序列（新结构统一改用 identity，不再需要）
DROP SEQUENCE IF EXISTS "public"."chat_memory_id_seq";
DROP SEQUENCE IF EXISTS "public"."knowledge_base_id_seq";
DROP SEQUENCE IF EXISTS "public"."mcp_information_id_seq";
DROP SEQUENCE IF EXISTS "public"."system_log_id_seq";
DROP SEQUENCE IF EXISTS "public"."user_id_seq";
DROP SEQUENCE IF EXISTS "public"."user_memory_id_seq";


-- ============================================================================
-- 1. 扩展
-- ============================================================================
-- knowledge_embedding.embedding 的 vector 类型依赖它
CREATE EXTENSION IF NOT EXISTS vector;


-- ============================================================================
-- 2. 枚举类型
-- ============================================================================
-- 与 Java 枚举一一对应，不要随意增删取值：
--   message_type  ← com.huzhijian.nexusagentweb.em.MessageType
--   upload_status ← com.huzhijian.nexusagentweb.em.UploadStatus
CREATE TYPE "public"."message_type" AS ENUM (
  'USER',
  'AI',
  'TOOL_EXECUTION_RESULT',
  'SYSTEM',
  'CUSTOM'
);

CREATE TYPE "public"."upload_status" AS ENUM (
  'PROCESSING',
  'SUCCESS',
  'FAILED'
);


-- ============================================================================
-- 3. 表结构
-- ----------------------------------------------------------------------------
--  主键策略统一说明
--  各实体的 @TableId 多数未指定 type，MyBatis-Plus 会走全局默认 ASSIGN_ID
--  （由应用生成雪花 ID）；而 ChatMemoryMapper.xml 的自定义 insertBatch 又**不带 id**，
--  依赖数据库生成。因此所有 id 列统一用：
--      bigint GENERATED BY DEFAULT AS IDENTITY
--  「BY DEFAULT」而不是「ALWAYS」是关键 —— 这样既接受应用显式传入的雪花 ID，
--  也支持不传时由数据库自增。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 3.1 users —— 账号
-- ---------------------------------------------------------------------------
-- 登录/注册全部以 email 为依据（UserServiceImpl: query().eq("email", email).one()），
-- 而 MyBatis-Plus 的 .one() 在命中多行时会抛异常，所以 email 的**唯一约束是硬需求**，
-- 不是可选项。
CREATE TABLE "public"."users" (
  "id"            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email"         varchar(255) NOT NULL,
  "username"      varchar(255) NOT NULL,
  -- bcrypt 结果固定 60 字符；允许为空（可先用验证码登录，之后再设置密码）
  "password"      varchar(60),
  "avatar_img"    varchar(512),
  "register_time" timestamptz  NOT NULL DEFAULT current_timestamp,
  "api_quota"     smallint     NOT NULL DEFAULT 100,
  "github_id"     varchar(255),
  CONSTRAINT uk_users_email UNIQUE ("email")
);
COMMENT ON TABLE  "public"."users"            IS '用户表';
COMMENT ON COLUMN "public"."users"."email"    IS '邮箱，登录与注册的唯一凭据';
COMMENT ON COLUMN "public"."users"."password" IS 'bcrypt 加密后的密码，可为空';
COMMENT ON COLUMN "public"."users"."api_quota" IS 'API 调用配额';

-- ---------------------------------------------------------------------------
-- 3.2 user_config —— 用户 API 配置（与 users 一对一）
-- ---------------------------------------------------------------------------
-- 与旧结构的差异：
--   · 删除了 user_default 列：数据库里有，但 UserConfig 实体中没有对应字段，代码从不读写
--   · mcp_token 由 char(128) 改为 varchar(512)：
--     Encryptors.text 输出十六进制，长度 = (16字节IV + 明文长度) × 2。
--     ModelScope 的 token 一旦超过 48 字符，char(128) 就会溢出报错。
--   · salt 保持 char(16)：KeyGenerators.string() 生成 8 字节 → 16 位十六进制，正好 16
--   · llm_api_token 由 json 改为 jsonb（可索引、写入即校验、去重）
CREATE TABLE "public"."user_config" (
  "user_id"       bigint      NOT NULL PRIMARY KEY,
  "llm_api_token" jsonb       NOT NULL DEFAULT '[]'::jsonb,
  "mcp_token"     varchar(512),
  "salt"          char(16)
);
COMMENT ON TABLE  "public"."user_config"                IS '用户配置信息（LLM 密钥 / MCP Token，均加密存储）';
COMMENT ON COLUMN "public"."user_config"."user_id"      IS '主键，同时是一对一外键';
COMMENT ON COLUMN "public"."user_config"."llm_api_token" IS 'LLM 配置数组，含加密后的 API Key';
COMMENT ON COLUMN "public"."user_config"."mcp_token"    IS '加密后的 MCP Token';
COMMENT ON COLUMN "public"."user_config"."salt"         IS '本用户专属加密盐值';

-- ---------------------------------------------------------------------------
-- 3.3 chat_memory —— 会话消息（LangChain4j 序列化后的消息 JSON）
-- ---------------------------------------------------------------------------
-- 一行 = 一条消息。ChatMemoryMapper 的自定义查询与 PgChatMemoryStore 都依赖它。
-- 注意：**有意不绑外键** —— 见 开发日志.md 4.20（新会话先插列表行、标题异步更新，
-- 绑外键会让插入顺序变复杂）。
CREATE TABLE "public"."chat_memory" (
  "id"         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"    bigint       NOT NULL,
  "content"    jsonb        NOT NULL,
  -- 使用自定义枚举；JDBC 侧需要 stringtype=unspecified 才能正常写入 jsonb
  "type"       "public"."message_type" NOT NULL,
  -- 刻意不加 ON DELETE：会话消息按 session_id 整体清理，不依赖级联
  "session_id" uuid         NOT NULL,
  "create_at"  timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  "public"."chat_memory"             IS '会话消息表';
COMMENT ON COLUMN "public"."chat_memory"."user_id"   IS '用户ID，方便全局查找';
COMMENT ON COLUMN "public"."chat_memory"."content"   IS '内容（LangChain4j ChatMessage 的 JSON）';
COMMENT ON COLUMN "public"."chat_memory"."type"      IS '消息类型';
COMMENT ON COLUMN "public"."chat_memory"."session_id" IS '会话ID';

-- ---------------------------------------------------------------------------
-- 3.4 chat_history_list —— 会话列表
-- ---------------------------------------------------------------------------
-- 主键是 session_id（实体 ChatHistoryList 用 @TableId 标在 sessionId 上）。
-- title 由异步任务生成后回写，失败时降级为用户问题前 255 字符。
-- 同样有意不绑外键。
CREATE TABLE "public"."chat_history_list" (
  "session_id"  uuid         NOT NULL PRIMARY KEY,
  "user_id"     bigint       NOT NULL,
  "title"       varchar(255),
  "create_time" timestamptz  NOT NULL DEFAULT current_timestamp,
  "update_time" timestamptz  NOT NULL DEFAULT current_timestamp
);
COMMENT ON TABLE  "public"."chat_history_list" IS '会话列表（含标题）';

-- ---------------------------------------------------------------------------
-- 3.5 user_memory —— 用户长期记忆
-- ---------------------------------------------------------------------------
-- ⚠️ source 由 char(32) 改为 varchar(64)：
--    MemoryTool.saveLongMemory 会把**会话 ID（UUID，36 字符）**写进 source，
--    char(32) 装不下，插入时会报 value too long for type character(32)。
-- 长期记忆当前走 SQL LIKE 模糊检索（向量检索的代码被注释掉了），
-- 因此这里**故意不加 embedding 列** —— 等决策 D4 明确后再加（见重构计划 P2-7）。
CREATE TABLE "public"."user_memory" (
  "id"        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"   bigint      NOT NULL,
  "content"   text        NOT NULL,
  "source"    varchar(64),
  "create_at" date        NOT NULL DEFAULT current_date
);
COMMENT ON TABLE  "public"."user_memory"          IS '用户长期记忆';
COMMENT ON COLUMN "public"."user_memory"."source" IS '来源会话 ID';

-- ---------------------------------------------------------------------------
-- 3.6 sys_file —— 上传文件元数据
-- ---------------------------------------------------------------------------
-- 依据（旧库中该表已丢失，完全由代码推导）：
--   domain/SysFile.java + mapper/FileMapper.xml 的 resultMap
--   写入路径：FileServiceImpl.uploadFile() → MyBatis-Plus saveBatch
-- 注意：SysFile 用 @TableId(type = IdType.ASSIGN_ID)，id 由应用生成；
--       这里仍用 GENERATED BY DEFAULT AS IDENTITY，两种方式都兼容。
CREATE TABLE "public"."sys_file" (
  "id"            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"       bigint       NOT NULL,
  -- OSS 地址。正常约 85 字符，但中文文件名会被 URL 编码膨胀，故放宽
  "file_url"      varchar(512),
  "file_name"     varchar(255),
  "file_size"     bigint,
  -- ⚠️ FileServiceImpl 失败时写入 substring(msg, 0, 450)，必须 ≥450，否则截断报错
  "fail_reason"   varchar(500),
  "upload_status" "public"."upload_status",
  "create_time"   timestamptz  NOT NULL DEFAULT current_timestamp,
  "extension"     varchar(64),
  -- BizType 枚举（KNOWLEDGE / CHAT）：未使用 @EnumValue，按枚举名存字符串
  "biz_type"      varchar(64)
);
COMMENT ON TABLE  "public"."sys_file"             IS '上传文件元数据';
COMMENT ON COLUMN "public"."sys_file"."biz_type"  IS '业务类型：KNOWLEDGE / CHAT';

-- ---------------------------------------------------------------------------
-- 3.7 knowledge_base —— 知识库
-- ---------------------------------------------------------------------------
-- id 保持 int4：实体 KnowledgeBase 的 id 字段是 Integer，改 bigint 需要同时改代码
CREATE TABLE "public"."knowledge_base" (
  "id"            integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"       bigint       NOT NULL,
  "name"          varchar(100) NOT NULL,
  "describe"      varchar(500),
  "is_public"     boolean      NOT NULL DEFAULT false,
  "language_code" varchar(10)
);
COMMENT ON TABLE "public"."knowledge_base" IS '知识库定义';

-- ---------------------------------------------------------------------------
-- 3.8 knowledge_base_file —— 知识库与文件的关联 + 向量化状态
-- ---------------------------------------------------------------------------
-- 实体 KnowledgeBaseFile **没有 id 字段**，因此用 (knowledge_base_id, file_id)
-- 复合主键表达业务约束：同一文件在同一知识库中只能出现一次。
-- ⚠️ file_name 是旧库**缺失**的列：KnowledgeBaseServiceImpl.insertKnowledge 会写入它、
--    KnowledgeBaseFileMapper.xml 的 resultMap 也映射它，缺列会导致入库与详情查询双双报错。
--    （顺带：旧 resultMap 里把它错写成 column="fail_name"，属于笔误，代码侧已一并修正）
CREATE TABLE "public"."knowledge_base_file" (
  "knowledge_base_id" integer NOT NULL,
  "file_id"           bigint  NOT NULL,
  "file_name"         varchar(255),
  "status"            "public"."upload_status",
  "fail_reason"       varchar(500),
  PRIMARY KEY ("knowledge_base_id", "file_id")
);
COMMENT ON TABLE "public"."knowledge_base_file" IS '知识库文件关联与向量化状态';

-- ---------------------------------------------------------------------------
-- 3.9 knowledge_embedding —— 向量存储（LangChain4j PgVectorEmbeddingStore 使用）
-- ---------------------------------------------------------------------------
-- ⚠️ 与旧库的关键差异：embedding 由**无维度**的 vector 改为 vector(1024)。
--    原因：pgvector 无法在无维度列上建索引，旧结构导致 RAG 检索是全表扫描 + 全量距离计算；
--    且无维度时换错向量模型不会被拦住。
--    维度来源：application-prod.yml 的 text-embedding-v4 / dimensions: 1024。
--    **换向量模型必须同步改这里并重建全部向量。**
-- 应用侧 PgVectorEmbeddingFactory 也会以 createTable(true) 建它，
-- 但因为表已存在不会覆盖，所以这里显式给出定义才是权威。
CREATE TABLE "public"."knowledge_embedding" (
  "embedding_id" uuid         NOT NULL PRIMARY KEY,
  "embedding"    "public"."vector"(1024),
  "text"         text,
  "metadata"     jsonb
);
COMMENT ON TABLE  "public"."knowledge_embedding" IS '知识库向量（由 LangChain4j 读写）';

-- ---------------------------------------------------------------------------
-- 3.10 mcp_information —— MCP 服务配置
-- ---------------------------------------------------------------------------
-- 有意不绑外键（同 chat_memory）。
-- 唯一约束 (user_id, str_id)：str_id 是 MCP 供应方（ModelScope）的稳定标识，
-- McpInformationServiceImpl.saveMcp 正是按 (user_id, str_id) 判断「新增还是更新」，
-- 加唯一约束可防止并发或重复提交产生重复记录。
CREATE TABLE "public"."mcp_information" (
  "id"          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar(255) NOT NULL,
  "url"         varchar(500) NOT NULL,
  "description" varchar(500),
  "header"      jsonb        NOT NULL DEFAULT '{}'::jsonb,
  "user_id"     bigint       NOT NULL,
  "type"        varchar(20),
  "logo_url"    varchar(500),
  "available"   boolean      NOT NULL DEFAULT true,
  "str_id"      varchar(255),
  CONSTRAINT uk_mcp_user_strid UNIQUE ("user_id", "str_id")
);
COMMENT ON TABLE  "public"."mcp_information"            IS 'MCP 配置信息';
COMMENT ON COLUMN "public"."mcp_information"."available" IS '是否可用（健康检查失败会置 false）';
COMMENT ON COLUMN "public"."mcp_information"."str_id"   IS 'MCP 供应方的稳定标识';

-- ---------------------------------------------------------------------------
-- 3.11 system_log —— AI / 系统日志
-- ---------------------------------------------------------------------------
-- LogTool.recordLog 提示 AI「内容不超过 1000 个字」，varchar 按字符计数，1024 够用。
CREATE TABLE "public"."system_log" (
  "id"         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content"    jsonb,
  "type"       varchar(16),
  "ai_message" varchar(1024),
  "cost_ms"    integer,
  "create_at"  timestamptz  NOT NULL DEFAULT current_timestamp
);
COMMENT ON TABLE  "public"."system_log"             IS '系统日志表';
COMMENT ON COLUMN "public"."system_log"."content"   IS '具体内容，比如方法名等';
COMMENT ON COLUMN "public"."system_log"."type"      IS 'AI / System';
COMMENT ON COLUMN "public"."system_log"."ai_message" IS 'AI 信息';
COMMENT ON COLUMN "public"."system_log"."cost_ms"   IS '方法耗时';

-- ---------------------------------------------------------------------------
-- 3.12 skill_mcp_information —— Skill 与 MCP 的注册表
-- ---------------------------------------------------------------------------
-- 实体 SkillMcpInformation 与 SkillMcpInformationMapper 映射此表，但旧库中没有它，
-- 属于「代码有、表没有」。这里按实体补上，使该代码路径不至于是坏的。
--
-- ⚠️ 该功能当前**完全未被调用**（ChatContextFactory 没有接入 Skills）。
--    决策 D3 已定为「本地目录扫描」方案，P2-1 很可能调整本表结构。
CREATE TABLE "public"."skill_mcp_information" (
  "id"          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar(255) NOT NULL,
  -- true = MCP 服务（source_path 存 URL）；false = Skill（source_path 存本地目录）
  "is_mcp"      boolean     NOT NULL DEFAULT false,
  "source_path" varchar(500) NOT NULL,
  "user_id"     bigint,
  "is_public"   boolean     NOT NULL DEFAULT false
);
COMMENT ON TABLE  "public"."skill_mcp_information"             IS 'Skill / MCP 注册表';
COMMENT ON COLUMN "public"."skill_mcp_information"."is_mcp"    IS 'true=MCP，false=Skill';
COMMENT ON COLUMN "public"."skill_mcp_information"."source_path" IS 'MCP 为 URL，Skill 为本地目录路径';


-- ============================================================================
-- 4. 外键
-- ============================================================================
-- 只给「父行不存在时子行毫无意义」的关系加外键。
-- 刻意**不加**外键的表（沿用原作者的设计决定，见 开发日志.md 4.20）：
--   chat_memory / chat_history_list / mcp_information
-- 原因：这些表存在「先插子行、父信息异步补」的写入顺序，绑外键会让流程变复杂。
ALTER TABLE "public"."user_config"
  ADD CONSTRAINT fk_user_config_user FOREIGN KEY ("user_id")
  REFERENCES "public"."users" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."knowledge_base_file"
  ADD CONSTRAINT fk_kbf_knowledge FOREIGN KEY ("knowledge_base_id")
  REFERENCES "public"."knowledge_base" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."knowledge_base_file"
  ADD CONSTRAINT fk_kbf_file FOREIGN KEY ("file_id")
  REFERENCES "public"."sys_file" ("id") ON DELETE CASCADE;

ALTER TABLE "public"."skill_mcp_information"
  ADD CONSTRAINT fk_skill_mcp_user FOREIGN KEY ("user_id")
  REFERENCES "public"."users" ("id") ON DELETE CASCADE;


-- ============================================================================
-- 5. 索引
-- ============================================================================
-- 每一条都对应代码里真实出现的查询条件（附出处），不做无依据的加索引。

-- 会话消息：所有历史读取都按 session_id 过滤
--   ChatMemoryMapper.getAllByMemoryId / getAllByMemoryIdAndUserId / getCountByMemoryId
CREATE INDEX idx_chat_memory_session_id ON "public"."chat_memory" ("session_id");
-- 越权修复后，对外读历史同时过滤 user_id
CREATE INDEX idx_chat_memory_user_id    ON "public"."chat_memory" ("user_id");

-- 会话列表：ChatHistoryListServiceImpl.getList → where user_id order by update_time desc
CREATE INDEX idx_chat_history_list_user_upd
  ON "public"."chat_history_list" ("user_id", "update_time" DESC);

-- 长期记忆：UserMemoryServiceImpl.getMemory → where user_id (+ content LIKE)
CREATE INDEX idx_user_memory_user_id ON "public"."user_memory" ("user_id");

-- 上传文件：FileServiceImpl.getFileByUserId → where user_id (+ biz_type, file_name LIKE)
CREATE INDEX idx_sys_file_user_biz ON "public"."sys_file" ("user_id", "biz_type");

-- 知识库：KnowledgeBaseServiceImpl.getKnowledgeList → where user_id
CREATE INDEX idx_knowledge_base_user_id ON "public"."knowledge_base" ("user_id");

-- MCP：McpInformationServiceImpl.getMcp → where user_id and id in (...)
--      （user_id 上的索引；唯一约束 uk_mcp_user_strid 已覆盖 (user_id, str_id)）
CREATE INDEX idx_mcp_information_user_id ON "public"."mcp_information" ("user_id");

-- 系统日志：按时间倒序查看
CREATE INDEX idx_system_log_create_at ON "public"."system_log" ("create_at" DESC);

-- 向量索引：PgVectorEmbeddingStore 的相似度检索用余弦距离（<=>），故用 vector_cosine_ops。
-- 这是 HNSW（近似最近邻），查询快、构建慢；知识库数据量很小时也可改用 ivfflat。
CREATE INDEX idx_knowledge_embedding_hnsw
  ON "public"."knowledge_embedding" USING hnsw ("embedding" vector_cosine_ops);


-- ============================================================================
-- 6. 未纳入本文件的已知问题（需要改代码，不是改表）
-- ============================================================================
-- 6.1 UserMemoryMapper.xml 的 search 语句是坏的：它 SELECT 了 user_memory 表中
--     并不存在的 category 与 embedding 两列。该方法是死代码（UserMemoryServiceImpl
--     .searchMemory 从未被调用，MemoryTool 走的是 LIKE 查询），所以暂时不报错，
--     但只要有人调用就会失败。→ 归入重构计划 P2-7（长期记忆检索方案）一起处理。
--
-- 6.2 User 实体缺少 @TableId：users.id 是主键，但实体上没有标注。
--     MyBatis-Plus 对「无主键实体」的 getById / updateById / removeById 会失败。
--     本文件已给出 users 主键，代码侧需补 @TableId（一行）。
--
-- 6.3 knowledge_base_file 的业务语义：知识库详情返回的文件列表实际取自
--     fileService.queryFileByids(...)（即 sys_file），表里的 file_name 目前只是冗余留存。
--     将来若确定不再需要，可考虑删列。
-- ============================================================================
